### ISSUE TITLE
sshnodefile not working properly

### ISSUE THREAD

**Issue by prietyc123** [mohammedzee1000/ci-firewall#11]
Random machine ssh are happening even though we pass `--name` to the json file or we use toolkit.

Logs which shows this behaviour https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4539/pull-ci-openshift-odo-master-psi-kubernetes-integration-e2e/1374676213695516672

**Comment by dharmit** [comment]
```
 + tar -xzf ci-firewall-linux-amd64.tar.gz
+ ./ci-firewall request --sendqueue amqp.ci.queue.minikube.send --sendtopic amqp.ci.topic.minikube.send --runscript scripts/kubernetes-all-test.sh --timeout 2h15m
Following jenkins build 267
[ssh:Windows 10] !!!running tests on node Windows 10 via ssh!!!
[ssh:Windows 10] Executing command [rm -rf amqp_ci_rcv_odo-minikube-pr-build_PR_4539]
[ssh:Windows 10] Executing command [mkdir -p amqp_ci_rcv_odo-minikube-pr-build_PR_4539/repo]
[ssh:Windows 10] Executing command [git clone https://github.com/openshift/odo amqp_ci_rcv_odo-minikube-pr-build_PR_4539/repo]
[ssh:Windows 10] Cloning into 'amqp_ci_rcv_odo-minikube-pr-build_PR_4539/repo'...
[ssh:Windows 10] Updating files:  16% (918/5421)
```

Tests should execute on Fedora 32 but they're running on Windows 10.

**Comment by anandrkskd** [comment]
I have researched on this issue and found that the test odo-e2e-build/minishift/minikube are using an exchange of type `fanout`, so in our case all the tests are trigger 3 times on all the nodes that are using the queue binded by that exchange.

To solve this problem we need to change the exchange the type from fanout to direct, this will require changes on ci_scripts on odo, creating new exchange for all the queue and code changes on ci-firewall.

**Comment by anandrkskd** [comment]
This [PR](https://github.com/mohammedzee1000/ci-firewall/pull/17) changes exchange from fanout to direct.
