### ISSUE TITLE
Trigger ci firewall scripts for master on release repo

### ISSUE THREAD

**Issue by prietyc123** [mohammedzee1000/ci-firewall#8]
https://github.com/openshift/odo/issues/4522

**Comment by rnapoles-rh** [comment]
@prietyc123 do you mean trigger PSI tests ?

**Comment by prietyc123** [comment]
> @prietyc123 do you mean trigger PSI tests ?

yes.

**Comment by prietyc123** [comment]
https://github.com/openshift/odo/issues/4522#issuecomment-810771993
